# Schema for the configuration files of the people module.

people.type.*:
  type: config_entity
  label: 'People type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'

action.configuration.people_create_user:
  type: action_configuration_default
  label: 'Create user account for selected people'
