# Schema for the configuration files of the move_order module.

move_order.type.*:
  type: config_entity
  label: 'Move order type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
