# Schema for the configuration files of the subinventory module.

cbo_inventory.type.*:
  type: config_entity
  label: 'Subinventory type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'

cbo_item.type.*.third_party.cbo_inventory:
  type: mapping
  label: 'Inventory settings for this item type'
  mapping:
    inventory_item:
      type: boolean
      label: 'Enable to stock and transact item in Inventory.'
