# @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php

sudo: false

dist: precise

php:
  - 7.1
  - 7.0

branches:
  except:
    - "7.x-1.x"

matrix:
  fast_finish: true

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

    # The environment to use, supported are: drupal-7, drupal-8
    - DRUPAL_ENVIRONMENT="drupal-8"
    - DRUPAL_CORE_BRANCH="8.6.x"

    # Drupal specific variables.
    - DRUPAL_DB="drupal_travis_db"
    - DRUPAL_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
    # Note: Do not add a trailing slash here.
    - DRUPAL_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_WEBSERVER_PORT="8080"


before_install:
  # Remove xdebug. We aren't generating code coverage, and it slows down Composer.
  - phpenv config-rm xdebug.ini || true
  # Add the oauth token to prevent GitHub timeouts.
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer global require "hirak/prestissimo:^0.3"
  - composer global require "lionsad/drupal_ti:dev-master#0d7c41abd1efa11726d7c908ae7a39bbeea905df"
  - composer global require "squizlabs/php_codesniffer:2.*"

install:
  # Installed after Drush to prevent Composer conflicts around symfony/yaml.
  - composer global require "drupal/coder:8.2.*"
  - phpcs --config-set installed_paths $HOME/.composer/vendor/drupal/coder/coder_sniffer


script:
  - phpcs --standard=phpcs.xml src -s
  - phpcs --standard=phpcs.xml modules -s
  - phpcs --standard=phpcs.xml tests -s
  - phpcs --standard=phpcs.xml e_invoice_cr.module -s

notifications:
  email: false
