# Schema for the configuration files of the small box module.

block.settings.small_box_block:
  type: block_settings
  label: 'Small box block'
  mapping:
    content:
      type: string
      label: 'Content'
    title:
      type: string
      label: 'Title'
    icon:
      type: string
      label: 'Icon'
    link:
      type: string
      label: 'Link'
    col_classes:
      type: string
      label: 'Col classes'
    box_classes:
      type: string
      label: 'Box classes'
