# Schema for the configuration files of the item module.

cbo_item.type.*:
  type: config_entity
  label: 'Item type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'

cbo_item.category.*:
  type: config_entity
  label: 'Item category'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
