image: yanniboi/drupal

variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: db
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  COMPOSER_ALLOW_SUPERUSER: '1'
  COMPOSER_EXIT_ON_PATCH_FAILURE: '1'
  DRUPAL_BUILD_ROOT: "$CI_BUILDS_DIR/drupal"
  DRUPAL_VERSION_TYPE: 'supported'

cache:
  paths:
    - .cache

# General set up of our environment and code.
before_script:
  - composer self-update
  - composer global require hirak/prestissimo

coder:
  cache:
    key: 'coder'
  except:
    refs:
      - schedules
  script:
    - composer global require drupal/coder:^8.3.1 dealerdirect/phpcodesniffer-composer-installer
    - ~/.composer/vendor/bin/phpcs --standard=Drupal -p --colors .

.phpunit:
  script:
    - ./.gitlab-ci/setup.sh
    - cd $DRUPAL_BUILD_ROOT
    - $CI_PROJECT_DIR/.gitlab-ci/phpunit.sh

drupal-supported:
  extends: .phpunit

drupal-security:
  extends: .phpunit
  variables:
    DRUPAL_VERSION_TYPE: 'security'

drupal-supported-dev:
  extends: .phpunit
  only:
    refs:
      - schedules
  variables:
    DRUPAL_VERSION_TYPE: 'supported-dev'

drupal-dev:
  extends: .phpunit
  only:
    refs:
      - master
      - schedules
  allow_failure: true
  variables:
    DRUPAL_VERSION_TYPE: 'dev'
