contacts_dbs.workforce.*:
  type: config_entity
  label: 'DBS Workforce'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Name'
    valid:
      type: integer
      label: 'Valid for (years)'
    alternatives:
      type: sequence
      label: 'Alternatives'
      sequence:
        type: string
        label: 'Alternative'
