path:
  - permissions
plugin: add
actions:
  'cancel account':
    value: 'cancel account'
  'change own username':
    value: 'change own username'
  'use text format basic_html':
    value: 'use text format basic_html'
