path:
  - permissions
plugin: add
actions:
  'access administration pages':
    value: 'access administration pages'
  'access content overview':
    value: 'access content overview'
  'access files overview':
    value: 'access files overview'
  'access site in maintenance mode':
    value: 'access site in maintenance mode'
  'access user profiles':
    value: 'access user profiles'
  'administer nodes':
    value: 'administer nodes'
  'administer taxonomy':
    value: 'administer taxonomy'
  'administer users':
    value: 'administer users'
  'bypass node access':
    value: 'bypass node access'
  'create url aliases':
    value: 'create url aliases'
  'delete all revisions':
    value: 'delete all revisions'
  'revert all revisions':
    value: 'revert all revisions'
  'view all revisions':
    value: 'view all revisions'
  'view own unpublished content':
    value: 'view own unpublished content'
  'view the administration theme':
    value: 'view the administration theme'
