centred:
  name: 'Centred'
  description: 'Centred is a minimalist skin with a centred title and menu below.'
  screenshot: 'skins/centred/screenshot.png'
chocolate:
  name: 'Chocolate'
  description: 'An earth toned brown and green skin with a slender headline font.'
  screenshot: 'skins/chocolate/screenshot.png'
jester:
  name: 'Jester'
  description: 'Deep red nav bar with large font size.'
  screenshot: 'skins/jester/screenshot.png'
orangery:
  name: 'Orangery'
  description: 'A bold look featuring deep orange with purple, olive and turquoise accents.'
  screenshot: 'skins/orangery/screenshot.png'
spring:
  name: 'Spring'
  description: 'Fresh spring colours with purples and green.'
  screenshot: 'skins/spring/screenshot.png'

