name: 'Products'
type: module
description: 'The products.'
# core: 8.x
package: 'IDCP'
dependencies:
  - idcp_core
  - server
# Information added by Drupal.org packaging script on 2018-05-20
version: '8.x-1.x-dev'
core: '8.x'
project: 'products'
datestamp: 1526827989
