entity.products.add_form:
  route_name: entity.products.add_page
  title: 'Add Products'
  appears_on:
    - entity.products.collection
entity.products_type.add_form:
  route_name: entity.products_type.add_form
  title: 'Add Products type'
  appears_on:
    - entity.products_type.collection

