add products entities:
  title: 'Create new Products entities'

administer products entities:
  title: 'Administer Products entities'
  description: 'Allow to access the administration form to configure Products entities.'
  restrict access: true

delete products entities:
  title: 'Delete Products entities'

edit products entities:
  title: 'Edit Products entities'

view published products entities:
  title: 'View published Products entities'

view unpublished products entities:
  title: 'View unpublished Products entities'

view all products revisions:
  title: 'View all Products revisions'

revert all products revisions:
  title: 'Revert all Products revisions'
  description: 'Role requires permission <em>view Products revisions</em> and <em>edit rights</em> for products entities in question or <em>administer products entities</em>.'

delete all products revisions:
  title: 'Delete all revisions'
  description: 'Role requires permission to <em>view Products revisions</em> and <em>delete rights</em> for products entities in question or <em>administer products entities</em>.'
