
# Products menu items definition
entity.products.collection:
  title: 'Products list'
  route_name: entity.products.collection
  description: 'List Products entities'
  parent: system.admin_structure
  weight: 100


# Products type menu items definition
entity.products_type.collection:
  title: 'Products type'
  route_name: entity.products_type.collection
  description: 'List Products type (bundles)'
  parent: system.admin_structure
  weight: 99

