path:
  - permissions
plugin: add
actions:
  'create people content':
    value: 'create people content'
  'delete own people content':
    value: 'delete own people content'
  'edit own people content':
    value: 'edit own people content'
