# Schema for the configuration files of the job module.

job.group.*:
  type: config_entity
  label: 'Job group'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
