# Schema for the configuration files of the crm_core_activity module.

crm_core_activity.type.*:
  type: config_entity
  label: 'Activtiy type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    activity_string:
      type: string
      label: 'Text describing the relationship between the contact and this activity.'
    plugin_id:
      type: string
      label: 'Plugin ID'
    plugin_configuration:
      type: crm_core_activity.configuration.[%parent.plugin_id]
      label: 'Plugin configuration'

# Schema for the plugin configuration.

crm_core_activity.configuration.generic:
  type: sequence
  label: 'Generic configuration'
