path:
  - permissions
plugin: add
actions:
  'create resource content':
    value: 'create resource content'
  'delete own resource content':
    value: 'delete own resource content'
  'edit own resource content':
    value: 'edit own resource content'
