path:
  - permissions
plugin: add
actions:
  'Administer groups':
    value: 'Administer groups'
  'bypass group access':
    value: 'bypass group access'
  'create group group':
    value: 'create group group'
