# Schema for the configuration files of the resource module.

cbo_resource.type.*:
  type: config_entity
  label: 'Resource type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
