# Schema for the configuration files of the supplier module.

supplier.type.*:
  type: config_entity
  label: 'Supplier type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
