# Schema for the views plugins of the Quick Code module.

views.area.quick_code_filter:
  type: views_area
  label: 'Quick code filter'
  mapping:
    quick_code_type:
      type: string
      label: 'Quick code type'
