# Schema for the configuration files of the quick code module.

quick_code.type.*:
  type: config_entity
  label: 'Quick code type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: label
      label: 'Description'
    hierarchy:
      type: boolean
      label: 'Hierarchy'
    code:
      type: boolean
      label: 'Code'
    encoding_rules:
      type: string
      label: 'Encoding rules'
    weight:
      type: integer
      label: 'Weight'

action.configuration.quick_code_enable_action:
  type: action_configuration_default
  label: 'Enable selected quick code configuration'

action.configuration.quick_code_disable_action:
  type: action_configuration_default
  label: 'Disable selected quick code configuration'

