uom.class.*:
  type: config_entity
  label: 'UOM class'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    base_uom:
      type: string
      label: 'Base UOM'
    description:
      type: string
      label: 'Description'

uom.uom.*:
  type: config_entity
  label: 'Unit of Measure'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    class:
      type: string
      label: 'UOM class'
    conversion_factor:
      type: float
      label: 'Conversion factor'
    description:
      type: string
      label: 'Description'
