# Schema for the configuration files of the organization module.

cbo_organization.type.*:
  type: config_entity
  label: 'Organization type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
