entity_extra_field.extra_field.*.*.*:
  type: config_entity
  label: Entity Field
  mapping:
    id:
      type: string
      label: Entity extra field identifier
    label:
      type: string
      label: Entity extra field label
    name:
      type: string
      label: Entity extra field machine name
    description:
      type: text
      label: Entity extra field description
    base_entity_type_id:
      type: string
      label: Base entity type identifier
    base_bundle_type_id:
      type: string
      label: Base bundle type identifier
    field_type_id:
      type: string
      label: Extra field type plugin identifier
    field_type_config:
      type: entity_extra_field.plugin.[%parent.field_type_id]
      label: Extra field type plugin configuration
    display:
      type: mapping
      label: Extra field display information
      mapping:
        type:
          type: string
          label: Extra field display type

entity_extra_field.plugin.block:
  type: mapping
  label: Extra field plugin block
  mapping:
    block_type:
      type: string
      label: Block identifier
    block_config:
      type: mapping
      label: Block configuration

entity_extra_field.plugin.views:
  type: mapping
  label: Extra field plugin views
  mapping:
    view_name:
      type: string
      label: Views machine name
    display:
      type: string
      label: Views display name
    arguments:
      type: string
      label: Views display arguments

entity_extra_field.plugin.token:
  type: mapping
  label: Extra field plugin token
  mapping:
    type:
      type: string
      label: Token text field type
    token:
      type: entity_extra_field.plugin.token.[type]

entity_extra_field.plugin.token.textfield:
  type: string
  label: Extra field plugin token text field

entity_extra_field.plugin.token.text_format:
  type: mapping
  label: Extra field plugin token text format
  mapping:
    value:
      type: string
      label: Extra field token value
    format:
      type: string
      label: Extra field token format
