<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * @file
 * Contains entity_theme_engine.module.
 */


/**
 * Implements hook_entity_view_alter().
 */
function entity_theme_engine_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  \Drupal::service('entity_theme_engine.entity_widget_service')->entityViewAlter($build, $entity, $display->getMode());
}

/**
 * Implements template_preprocess_hook().
 */
function template_preprocess_views_view_custom_wrapper(&$variables) {
  \Drupal::moduleHandler()->loadInclude('views', 'inc','views.theme');
  template_preprocess_views_view_unformatted($variables);
  $variables['options'] = $variables['view']->style_plugin->options;
}
