path:
- permissions
plugin: add
actions:
  'administer meta tags':
    value: 'administer meta tags'
  'administer redirect settings':
    value: 'administer redirect settings'
  'administer redirects':
    value: 'administer redirects'
