name: Config Actions
type: module
description: Enables modules to provide actions that modify configuration.
# core: 8.x

# Information added by Drupal.org packaging script on 2019-03-19
version: '8.x-1.1'
core: '8.x'
project: 'config_actions'
datestamp: 1553005391
