services:
  plugin.manager.config_actions_plugin:
    class: Drupal\config_actions\ConfigActionsPluginManager
    arguments: ['@container.namespaces', '@cache.discovery', '@module_handler']
  plugin.manager.config_actions_source:
    class: Drupal\config_actions\ConfigActionsSourceManager
    arguments: ['@container.namespaces', '@cache.discovery', '@module_handler']
  config_actions:
    class: Drupal\config_actions\ConfigActionsService
    arguments: ['@plugin.manager.config_actions_plugin', '@plugin.manager.config_actions_source', '@module_handler']
