<?php

/**
 * @file
 * Module related hook implementations for the contacts_log module.
 */

use Drupal\message\Entity\Message;
use Drupal\profile\Entity\Profile;
use Drupal\user\Entity\User;

/**
 * Implements hook_ENTITY_TYPE_insert() for profile.
 */
function contacts_log_profile_insert(Profile $profile) {
  \Drupal::service('contacts_log.profile_logger')->onInsert($profile);
}

/**
 * Implements hook_ENTITY_TYPE_update() for profile.
 */
function contacts_log_profile_update(Profile $profile) {
  \Drupal::service('contacts_log.profile_logger')->onUpdate($profile);
}

/**
 * Implements hook_ENTITY_TYPE_update() for user.
 */
function contacts_log_user_update(User $user) {
  \Drupal::service('contacts_log.user_logger')->onUpdate($user);
}
